version: 1
services:
  - name: django
    image: "python:3.9"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - port: 8000
    envs:
      - name: DJANGO_SETTINGS_MODULE
        value: "Personal_Assistant.settings"
    volumes:
      - name: django-volume
        mountPath: /app
