# Generated by Django 5.0.3 on 2024-04-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_note_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='name',
        ),
    ]
